services:
  coilcast:
    image: coilcast:latest
    build: .
    container_name: coilcast-app
    ports: 
      - "${HTTP_PORT}:8080"
    environment:
      # Coilcast application settings
      ADMIN_LOGIN: "${ADMIN_LOGIN}"
      ADMIN_PASS: "${ADMIN_PASS}"
      MUSIC_FOLDER: "${MUSIC_FOLDER}"
      DEBUG_MODE: "${DEBUG_MODE}"
      HTTP_PORT: "${HTTP_PORT}"
      # Database settings
      DB_TYPE: "${DB_TYPE}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
    volumes:
      - ./music:/app/coilcast/music
    networks:
      - coilcast
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: coilcast-db
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - coilcast
    restart: unless-stopped
    
networks:
  coilcast:
    driver: bridge

volumes:
  postgres-data:
